### ISSUE TITLE
42 Auth

### ISSUE THREAD

**Issue by kmlFaouzi** [LeetByteBuilders/TorrentFlix#3]

**Comment by kmlFaouzi** [comment]
Implement authentication using the 42 API (Intra) to enable users to log in with their 42 credentials. This feature will integrate the 42 OAuth authentication mechanism into the application, ensuring secure user access and seamless sign-in through the 42 platform.

**Comment by osallak** [comment]
i will close this issue since it's already open and here is it's reference #6
